### ISSUE TITLE
missmatch check digit

### ISSUE THREAD

**Issue by rG2ee** [AACEngineering/epcpy-tools#2]
Hi, 
at first thanks for your great effort to write this library! I just installed it and it works like a charm. However I noticed a minor missmatch to a website I found. 
For the GRAI-170 Tag from your tests I found that 
`decode_epc("0x37012a05f20000188000000000000000000000000000").barcode == '8003032000000000011'
decode_epc("0x37012a05f20000188000000000000000000000000000").values['serial_number'] == '1'`
With a serial number of '1' the second last digit is the check digit which is '1'.
When inserting this to http://convert.erfideo.com/Home
all values but the check digit (which is 9 on this website) does match.

May you explain weather the website yields wrong values or this a bug in the code?

Many Regards
Dennis

Edit1: Additionally the convert.erfideo.com truncates the epc_hex by one trailing '0'. Why are there different lenghts?

Edit2: Updated link.

**Comment by kluchrj** [comment]
Using GS1's official tool I am getting a 1 for the check digit: https://www.gs1.org/services/epc-encoderdecoder

![image](https://user-images.githubusercontent.com/10727645/138755113-9da7b43c-d4a6-41d6-96ea-6beb87c334b6.png)

[This other online converter](https://www.mimasu.nl/tag-encoding/tdt) also returned 1 for the check digit when I entered the EPC.

I am leaning towards saying that the erfideo website is doing something wrong here. I didn't actually open up the GS1 spec and hand calculate the value from that, but I think it's a pretty safe assumption since it doesn't agree with 3 other implementations.

**Comment by rG2ee** [comment]
Ok, thanks for the detailed response! It is good to know that there are several such tools for comparison. Shall I close this issue then?

**Comment by kluchrj** [comment]
I think it's safe to close it.
